name: alliya_kalenda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0-210.2.beta

dependencies:
  connectivity_plus: ^7.3.1
  file_picker: ^13.0.0
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  intl: ^0.20.3
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/branding/Alliya-Kalenda-app-icon-bigA-calendar-1024-rounded.png
    - assets/images/covers/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/Alliya-Kalenda-app-icon-bigA-calendar-1024-rounded.png
  remove_alpha_ios: true
  adaptive_icon_background: '#071D3B'
  adaptive_icon_foreground: assets/branding/Alliya-Kalenda-app-icon-bigA-calendar-1024-rounded.png
  macos:
    generate: true
  windows:
    generate: true
    image_path: assets/branding/Alliya-Kalenda-app-icon-bigA-calendar-1024-rounded.png
